In [1]:
import numpy as np

In [2]:
fixed_array = np.arange(10)

def f(x):
    return np.sum((x - fixed_array) ** 2)

f(0), f(1), f(2)

(285, 205, 145)

# Use `frompyfunc`

We can do the following, but:

- It's slow
- You can an array of `objects`

In [21]:
ff = np.frompyfunc(f, 1, 1)
ff([0,1,2])

array([285, 205, 145], dtype=object)

In [9]:
ff(np.arange(3))

array([285, 205, 145], dtype=object)

In [13]:
%timeit ff(np.arange(1000))

100 loops, best of 3: 9 ms per loop


# The numpy way

- Use of `asarray`
- Use of `...` and `None` in slicing

In [23]:
def fff(x):
    return np.sum((np.asarray(x)[...,None] - fixed_array)**2, axis=-1)

In [29]:
%timeit fff(np.arange(1000))

10000 loops, best of 3: 76.8 µs per loop


# Some explaination

In [34]:
# Try changing the shape
y = np.random.random(size=(5,2))
yy = y[...,None]

assert( y.shape + (1,) == yy.shape )
y - yy[...,0]

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [36]:
# Broadcast rules
xx = np.array([[1,2,3],[4,5,6]])
yy = np.array([1,2,3,4])
xx.shape, yy.shape

((2, 3), (4,))

In [38]:
zz = xx[...,None] - yy
zz.shape

(2, 3, 4)

In [39]:
zz

array([[[ 0, -1, -2, -3],
        [ 1,  0, -1, -2],
        [ 2,  1,  0, -1]],

       [[ 3,  2,  1,  0],
        [ 4,  3,  2,  1],
        [ 5,  4,  3,  2]]])

In [41]:
for i in range(2):
    for j in range(3):
        for k in range(4):
            assert zz[i][j][k] == xx[i][j] - yy[k]